tasks:
  - name: "Task 1"
    schedule: "0 */6 * * * *"  # Every 5 minutes
    command: "echo 'Hello from Task 1'"
  - name: "Task 2"
    schedule: "0 * * * * *"    # Every minute at the 0th seconds
    command: "echo 'Hello from Task 2'"
  - name: "Task 3"
    schedule: "*/5 * * * * *"  # Every 5 seconds
    function: "check(https://www.fanyamin.com)"